version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
